name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.9
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        pip install .
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')