name: pytest

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up Python 3.9
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install poetry
        poetry install
    - name: Test
      env:
        NAS_CREDS: ${{ secrets.NAS_CREDS }}
      run: |
        python -m pytest tests/