name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
        submodules: recursive
        ref: main


    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.8.5
      id: release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        root_options: "-vv"
    outputs:
      release: ${{ steps.release.outputs.released }}

  build_wheels:
    if: needs.release.outputs.release == 'true'
    name: Build wheels on ${{ matrix.python-version }}
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest] # Not supporting macos due to https://github.com/stbrumme/hash-library/pull/4/files not being resolved
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
        - uses: actions/checkout@v4.1.7
          with:
            submodules: recursive
            ref: main
      
        # Used to host cibuildwheel
        - uses: actions/setup-python@v5.1.1
          with:
            python-version: ${{ matrix.python-version }}

        - name: Upgrade pip
          run: python -m pip install --upgrade pip
    
        # - name: Install cibuildwheel
        #   run: python -m pip install cibuildwheel

        # - name: Build wheels
        #   run: python -m cibuildwheel --output-dir dist
        #     # to supply options, put them in 'env', like:
        #     # env:
        #     #   CIBW_SOME_OPTION: value
        #   env:
        #     CIBW_BUILD: "cp39-*64 cp310-*64 cp311-*64 cp312-*64"
        #     CIBW_BEFORE_BUILD: git submodule update --init --recursive && pip install .
        - name: Build wheels
          run: python -m pip wheel -w dist .
    
        - uses: actions/upload-artifact@v4.3.4
          with:
            path: ./dist/nas_unzip*.whl

  publish:
    runs-on: ubuntu-latest
    needs: [build_wheels]
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
        submodules: recursive
        ref: main

    - uses: actions/download-artifact@v4.1.8
      with:
        name: artifact
        path: dist

    - name: Check dist
      run: ls -R dist

    - name: Publish package distributions to GitHub Releases
      id: github-release
      uses: python-semantic-release/upload-to-gh-release@v9.8.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
